[package]
name = "wlb-cli"
version = "0.1.0"
authors = ["Alex Eubanks <endeavor@rainbowsandpwnies.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
wlb = {path = "../wlb"}